# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rogemin\PycharmProjects\MIPT-CODING_py_project\ui\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 552)
        MainWindow.setStyleSheet("* {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: none;\n"
"    color: #fff;\n"
"    font-family: Montserrat SemiBold;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"QScrollArea {\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #272b33;\n"
"    border: 2px solid #272b33;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #272b33;\n"
"    border: 2px solid #272b33;\n"
"     border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #272b33;\n"
"    border: 2px solid #272b33;\n"
"     border-radius: 5px;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    color: black;\n"
"    selection-background-color: #1f232a;\n"
"}\n"
"\n"
"QSlider::groove:horizontal { \n"
"    background-color: #272b33;\n"
"    border: 0px solid #272b33; \n"
"    height: 8px; \n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: rgb(64, 71, 85);\n"
"    border: 4px solid rgb(64, 71, 85); \n"
"    width: 10px; \n"
"    height: 10px; \n"
"    line-height: 10px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 9.45px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 9.45px;\n"
"}\n"
"\n"
"QScrollBar {              \n"
"    border: none;\n"
"    width: 10px;\n"
"    background: #272b33;\n"
"}\n"
"QScrollBar::handle {\n"
"    border-radius: 4px;\n"
"    background: #383e4a;\n"
"}\n"
"QScrollBar::sub-page {\n"
"    background: #272b33;\n"
"}\n"
"\n"
"QScrollBar::add-page {\n"
"    background: #272b33;\n"
"}\n"
"QScrollBar::add-line {       \n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openCSVButton = QtWidgets.QPushButton(self.centralwidget)
        self.openCSVButton.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.openCSVButton.setObjectName("openCSVButton")
        self.x_to_y_button = QtWidgets.QPushButton(self.centralwidget)
        self.x_to_y_button.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.x_to_y_button.setObjectName("x_to_y_button")
        self.y1_to_y2_button = QtWidgets.QPushButton(self.centralwidget)
        self.y1_to_y2_button.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.y1_to_y2_button.setObjectName("y1_to_y2_button")
        self.x1_to_y2_button = QtWidgets.QPushButton(self.centralwidget)
        self.x1_to_y2_button.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.x1_to_y2_button.setObjectName("x1_to_y2_button")
        self.x1_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.x1_line_edit.setGeometry(QtCore.QRect(100, 10, 131, 20))
        self.x1_line_edit.setInputMask("")
        self.x1_line_edit.setObjectName("x1_line_edit")
        self.x2_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.x2_line_edit.setGeometry(QtCore.QRect(240, 10, 131, 20))
        self.x2_line_edit.setObjectName("x2_line_edit")
        self.y1_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.y1_line_edit.setGeometry(QtCore.QRect(380, 10, 131, 20))
        self.y1_line_edit.setObjectName("y1_line_edit")
        self.y2_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.y2_line_edit.setGeometry(QtCore.QRect(520, 10, 131, 20))
        self.y2_line_edit.setObjectName("y2_line_edit")
        self.stylesDropdown = QtWidgets.QComboBox(self.centralwidget)
        self.stylesDropdown.setGeometry(QtCore.QRect(660, 10, 101, 22))
        self.stylesDropdown.setObjectName("stylesDropdown")
        self.methodsDropdown = QtWidgets.QComboBox(self.centralwidget)
        self.methodsDropdown.setGeometry(QtCore.QRect(10, 240, 81, 22))
        self.methodsDropdown.setObjectName("methodsDropdown")
        self.kLabel = QtWidgets.QLabel(self.centralwidget)
        self.kLabel.setGeometry(QtCore.QRect(10, 280, 81, 16))
        self.kLabel.setObjectName("kLabel")
        self.approxButton = QtWidgets.QToolButton(self.centralwidget)
        self.approxButton.setGeometry(QtCore.QRect(20, 170, 60, 60))
        self.approxButton.setStyleSheet("background-color: rgb(0, 132, 255);\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.approxButton.setIcon(icon)
        self.approxButton.setIconSize(QtCore.QSize(32, 32))
        self.approxButton.setObjectName("approxButton")
        self.approxLabel = QtWidgets.QLabel(self.centralwidget)
        self.approxLabel.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.approxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.approxLabel.setObjectName("approxLabel")
        self.toggleButton = QtWidgets.QToolButton(self.centralwidget)
        self.toggleButton.setGeometry(QtCore.QRect(785, 50, 41, 41))
        self.toggleButton.setStyleSheet("background-color: #272b33;\n"
"border-radius: 20px;\n"
"border: 3px solid rgb(0, 132, 255);\n"
"")
        self.toggleButton.setText("")
        self.toggleButton.setIcon(icon)
        self.toggleButton.setIconSize(QtCore.QSize(24, 24))
        self.toggleButton.setObjectName("toggleButton")
        self.toggleLabel = QtWidgets.QLabel(self.centralwidget)
        self.toggleLabel.setGeometry(QtCore.QRect(787, 30, 47, 13))
        self.toggleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.toggleLabel.setObjectName("toggleLabel")
        self.markerSizeSlider = QtWidgets.QSlider(self.centralwidget)
        self.markerSizeSlider.setGeometry(QtCore.QRect(770, 250, 161, 22))
        self.markerSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.markerSizeSlider.setObjectName("markerSizeSlider")
        self.lineDropdown = QtWidgets.QComboBox(self.centralwidget)
        self.lineDropdown.setGeometry(QtCore.QRect(840, 50, 91, 22))
        self.lineDropdown.setObjectName("lineDropdown")
        self.lineNLabel = QtWidgets.QLabel(self.centralwidget)
        self.lineNLabel.setGeometry(QtCore.QRect(840, 30, 47, 13))
        self.lineNLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineNLabel.setObjectName("lineNLabel")
        self.blueLineColorButton = QtWidgets.QToolButton(self.centralwidget)
        self.blueLineColorButton.setGeometry(QtCore.QRect(860, 120, 31, 31))
        self.blueLineColorButton.setStyleSheet("background-color: #1f232a;\n"
"border-radius: 15.45px;\n"
"border: 6px solid rgb(0, 11, 204);\n"
"")
        self.blueLineColorButton.setText("")
        self.blueLineColorButton.setObjectName("blueLineColorButton")
        self.redLineColorButton = QtWidgets.QToolButton(self.centralwidget)
        self.redLineColorButton.setGeometry(QtCore.QRect(900, 120, 31, 31))
        self.redLineColorButton.setStyleSheet("background-color: #1f232a;\n"
"border-radius: 15.45px;\n"
"border: 6px solid rgb(204, 0, 3);\n"
"")
        self.redLineColorButton.setText("")
        self.redLineColorButton.setObjectName("redLineColorButton")
        self.grayLineColorButton = QtWidgets.QToolButton(self.centralwidget)
        self.grayLineColorButton.setGeometry(QtCore.QRect(860, 160, 31, 31))
        self.grayLineColorButton.setStyleSheet("background-color: #1f232a;\n"
"border-radius: 15.45px;\n"
"border: 6px solid rgb(56, 62, 74);\n"
"")
        self.grayLineColorButton.setText("")
        self.grayLineColorButton.setObjectName("grayLineColorButton")
        self.whiteLineColorButton = QtWidgets.QToolButton(self.centralwidget)
        self.whiteLineColorButton.setGeometry(QtCore.QRect(900, 160, 31, 31))
        self.whiteLineColorButton.setStyleSheet("background-color: #1f232a;\n"
"border-radius: 15.45px;\n"
"border: 6px solid rgb(212, 212, 212);\n"
"")
        self.whiteLineColorButton.setText("")
        self.whiteLineColorButton.setObjectName("whiteLineColorButton")
        self.yellowLlineColorButton = QtWidgets.QToolButton(self.centralwidget)
        self.yellowLlineColorButton.setGeometry(QtCore.QRect(860, 200, 31, 31))
        self.yellowLlineColorButton.setStyleSheet("background-color: #1f232a;\n"
"border-radius: 15.45px;\n"
"border: 6px solid rgb(211, 197, 0);\n"
"")
        self.yellowLlineColorButton.setText("")
        self.yellowLlineColorButton.setObjectName("yellowLlineColorButton")
        self.brownLineColorButton = QtWidgets.QToolButton(self.centralwidget)
        self.brownLineColorButton.setGeometry(QtCore.QRect(900, 200, 31, 31))
        self.brownLineColorButton.setStyleSheet("background-color: #1f232a;\n"
"border-radius: 15.45px;\n"
"border: 6px solid rgb(113, 40, 0);\n"
"")
        self.brownLineColorButton.setText("")
        self.brownLineColorButton.setObjectName("brownLineColorButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(100, 50, 661, 491))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 651, 491))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.markerTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.markerTypeLabel.setGeometry(QtCore.QRect(770, 100, 71, 16))
        self.markerTypeLabel.setObjectName("markerTypeLabel")
        self.lineColorLabel = QtWidgets.QLabel(self.centralwidget)
        self.lineColorLabel.setGeometry(QtCore.QRect(860, 100, 71, 16))
        self.lineColorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lineColorLabel.setObjectName("lineColorLabel")
        self.triangleMarkerTypeButton = QtWidgets.QToolButton(self.centralwidget)
        self.triangleMarkerTypeButton.setGeometry(QtCore.QRect(790, 120, 31, 31))
        self.triangleMarkerTypeButton.setStyleSheet("")
        self.triangleMarkerTypeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/triangle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.triangleMarkerTypeButton.setIcon(icon1)
        self.triangleMarkerTypeButton.setIconSize(QtCore.QSize(36, 36))
        self.triangleMarkerTypeButton.setObjectName("triangleMarkerTypeButton")
        self.circleMarkerTypeButton = QtWidgets.QToolButton(self.centralwidget)
        self.circleMarkerTypeButton.setGeometry(QtCore.QRect(790, 160, 31, 31))
        self.circleMarkerTypeButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circleMarkerTypeButton.setIcon(icon2)
        self.circleMarkerTypeButton.setIconSize(QtCore.QSize(36, 36))
        self.circleMarkerTypeButton.setObjectName("circleMarkerTypeButton")
        self.squareMarketTypeButton = QtWidgets.QToolButton(self.centralwidget)
        self.squareMarketTypeButton.setGeometry(QtCore.QRect(790, 200, 31, 31))
        self.squareMarketTypeButton.setStyleSheet("")
        self.squareMarketTypeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.squareMarketTypeButton.setIcon(icon3)
        self.squareMarketTypeButton.setIconSize(QtCore.QSize(36, 36))
        self.squareMarketTypeButton.setObjectName("squareMarketTypeButton")
        self.markerSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.markerSizeLabel.setGeometry(QtCore.QRect(820, 270, 71, 16))
        self.markerSizeLabel.setObjectName("markerSizeLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openCSVButton.setText(_translate("MainWindow", "Open CSV"))
        self.x_to_y_button.setText(_translate("MainWindow", "x to y"))
        self.y1_to_y2_button.setText(_translate("MainWindow", "y1 to y2"))
        self.x1_to_y2_button.setText(_translate("MainWindow", "x1 to y2"))
        self.x1_line_edit.setPlaceholderText(_translate("MainWindow", "x1"))
        self.x2_line_edit.setPlaceholderText(_translate("MainWindow", "x2"))
        self.y1_line_edit.setPlaceholderText(_translate("MainWindow", "y1"))
        self.y2_line_edit.setPlaceholderText(_translate("MainWindow", "y2"))
        self.stylesDropdown.setProperty("placeholderText", _translate("MainWindow", "Style"))
        self.methodsDropdown.setProperty("placeholderText", _translate("MainWindow", "Methods"))
        self.kLabel.setText(_translate("MainWindow", "K = (...)"))
        self.approxLabel.setText(_translate("MainWindow", "Approx on/off"))
        self.toggleLabel.setText(_translate("MainWindow", "On/off"))
        self.lineDropdown.setProperty("placeholderText", _translate("MainWindow", "Style"))
        self.lineNLabel.setText(_translate("MainWindow", "Line N"))
        self.markerTypeLabel.setText(_translate("MainWindow", "Marker type"))
        self.lineColorLabel.setText(_translate("MainWindow", "Line color"))
        self.markerSizeLabel.setText(_translate("MainWindow", "Marker size"))
import ui.resources_rc
